"default settings
syntax on 

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch 

"plugins
call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'
"Plug 'jremmen/vim-ripgrep'
Plug 'tpope/vim-fugitive'
Plug 'leafgarland/typescript-vim'
Plug 'lyuts/vim-rtags'
Plug 'git@github.com:kien/ctrlp.vim.git'
Plug 'git@github.com:Valloric/YouCompleteMe.git'
Plug 'mbbill/undotree'

call plug#end()

"apply colorscheme
colorscheme gruvbox
set background=dark

"variable settings
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
let mapleader = " "

let g:netrw_browse_split = 2
let g:netrw_banner = 0
let g:netrw_winsize = 25
let g:ctrlp_use_caching = 0

"Key bindings to move easily between different vim windows
nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>l :wincmd l<CR>

"Key bindings for file explorer: you can also just use :Explore
nnoremap <leader>pv :wincmd v<bar> :Ex <bar> :vertical resize 30<CR>

"Key bindings for vertical resize
"horizontal resize is: ctrl+w + +/-
nnoremap <silent> <Leader>+ :vertical resize +5<CR>
nnoremap <silent> <Leader>- :vertical resize -5<CR>

"Key bindings for ycmcompleter
"use ctrl+o to go back after goto command
nnoremap <silent> <Leader>gd :YcmCompleter GoTo<CR>
"nnoremap <silent> <Leader>gf :YcmCompleter FixIt<CR>
nnoremap <silent> <Leader>gr :YcmCompleter GetDoc<CR>
nnoremap <silent> <Leader>gt :YcmCompleter GetType<CR>

"Key bindinds to make vertical and horizontal split in vim
nnoremap <silent> <C-W>v :vsp<CR>
nnoremap <silent> <C-W>h :sp<CR>

"Key bindings to move single lines up and down
nnoremap <silent> <C-down> :m+<CR>
nnoremap <silent> <C-up> :m-2<CR>

"Key bindings to copy independent of mode
"requires: sudo apt-get install vim-gtk
noremap <Leader>y "+y
noremap <Leader>p "+p

"Key bindings to move the entire text after cursor one line below
nnoremap <silent> <CR> i<CR><Esc><Esc>k$
